name: Check Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install -U flake8

    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=255 --statistics
